### ISSUE TITLE
Latest release breaks streetview

### ISSUE THREAD

**Issue by simonh1000** [allenhwkim/angularjs-google-maps#40]
Hi there,
I had been pulling your code directly from Github and my client reported a bug today.
I have the following markup

```
<map style="display:block;height:300px" center="[ 52.374304, 4.898723 ]" zoom="13" draggable="true" street-view="StreetViewPanorama(document.querySelector('#sv'), {position:new google.maps.LatLng(52.374304, 4.898723)})"/>
                            <marker position="[52.374304, 4.898723]" name="hello Vicky" draggable="true" on-dragend="dragEnd()"></marker>
                        </map>
```

and found this in the browser console.                      

```
Error: setStreetView: not an instance of StreetViewPanorama
Error
    at Error (native)
    at new re (https://maps.gstatic.com/intl/en_gb/mapfiles/api-3/17/1/main.js:13:610)
    at se (https://maps.gstatic.com/intl/en_gb/mapfiles/api-3/17/1/main.js:13:723)
    at Tl.setStreetView (https://maps.gstatic.com/intl/en_gb/mapfiles/api-3/17/1/main.js:26:909)
    at Tl.G.setValues (https://maps.gstatic.com/intl/en_gb/mapfiles/api-3/17/1/main.js:22:84)
    at new Tl (https://maps.gstatic.com/intl/en_gb/mapfiles/api-3/17/1/main.js:47:622)
    at initializeMap (http://rawgit.com/allenhwkim/angularjs-google-maps/master/dist/ng-map.js:124:23)
    at link (http://rawgit.com/allenhwkim/angularjs-google-maps/master/dist/ng-map.js:203:14)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.6/angular.js:6713:13)
    at compositeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.6/angular.js:6118:15) <map style="display:block;height:300px" center="[ 52.374304, 4.898723 ]" zoom="13" draggable="true" street-view="StreetViewPanorama(document.querySelector('#sv'), {position:new google.maps.LatLng(52.374304, 4.898723)})"> 
```

I've manually backed them down to the previous code base for the time being.  Let me know what you make of this.

**Comment by rasekar2000** [comment]
Can you please confirm whether StreetViewPanorama worked for you in this Angular Google Maps section? If so, can you please share some more detailed section of the code in http://plnkr.co/edit/?p=preview or so, Thanks in advance

**Comment by simonh1000** [comment]
The bug was fixed and street view works. Your link doesn't point to anything

**Comment by allenhwkim** [comment]
It seems working

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_street_view.html <https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_street_view.html>

Let me know if you have non-working example in plunker.

**Comment by rasekar2000** [comment]
I think i was mixing up , https://github.com/angular-ui/angular-google-maps/issues/286#issuecomment-71149946 .. Let me try your angularjs-google-maps projects and get back.. thanks .. 

@allenhwkim & @simonh1000 , I have not put any code.. I was requesting you to keep the code.. But now that I have this example, let me evaluate.. 

Thanks and Regards,
Raj

**Comment by qazn123** [comment]
Hi,

It appears that this error message "setStreetView: not an instance of StreetViewPanorama" is still showing in the console, but the streetview actually renders and works.

Any thought?

Thanks,
Quan
